### ISSUE TITLE
Create show all/filter page meny-bar comp

### ISSUE THREAD

**Issue by ElisyanBot** [ElisyanBot/PingstOSD#26]
### Task

  Create a meny-bar for the Show all objects page. 

### Completion

- [ ]   when the meny can show the current "object category" as a title.
- [ ]   when a sort and filter menu btn i displayed on the bar
- [ ]   when a searchbar-component is displayed on the bar
- [ ]   when its style like the [menu on the show all page in the webdesign](url)
- [ ]   when it works on mobile platforms
