### ISSUE TITLE
Create filter menu dropdown

### ISSUE THREAD

**Issue by ElisyanBot** [ElisyanBot/PingstOSD#27]
### Task

  Create a dropdown meny for filter by different tags. 

### Completion

- [x] when the dropdown can be shown/hide on a click event.
- [x] can take checkbox-item children
- [x] is styled like the [dropdown on show all page in the webdesign](https://www.figma.com/file/rrXWboida47CY0XreUJAbn/Pingst-%C3%B6sd-ver-2?node-id=0%3A1&t=W83n4kHv6utelQIb-0)
